/**
 * Export utilities for different formats
 */

import type { Summary } from './stores/appStore';

/**
 * Export summary as Markdown
 */
export function exportAsMarkdown(summary: Summary): string {
  const sections: string[] = [];

  // Title
  sections.push(`# ${summary.videoTitle || 'YouTube Video Summary'}\n`);

  // Metadata
  sections.push(`**Video URL:** ${summary.videoUrl}`);
  sections.push(`**Summary Mode:** ${summary.mode}`);
  sections.push(`**Generated:** ${new Date(summary.createdAt).toLocaleString()}\n`);
  if (summary.duration) {
    sections.push(`**Processing Time:** ${summary.duration}ms\n`);
  }

  sections.push('---\n');

  // Content
  sections.push(`## Summary\n`);
  sections.push(summary.content);
  sections.push('');

  // Timestamps
  if (summary.timestamps && summary.timestamps.length > 0) {
    sections.push(`## Key Timestamps\n`);
    summary.timestamps.forEach((ts) => {
      sections.push(`- **${ts.time}** - ${ts.text}`);
    });
    sections.push('');
  }

  // Citations
  if (summary.citations && summary.citations.length > 0) {
    sections.push(`## Citations\n`);
    summary.citations.forEach((citation, idx) => {
      sections.push(`${idx + 1}. ${citation}`);
    });
    sections.push('');
  }

  // Footer
  sections.push('---');
  sections.push('*Generated by AI-Powered YouTube Summarizer*');

  return sections.join('\n');
}

/**
 * Export summary as JSON
 */
export function exportAsJSON(summary: Summary): string {
  return JSON.stringify(summary, null, 2);
}

/**
 * Export summary as plain text
 */
export function exportAsText(summary: Summary): string {
  const sections: string[] = [];

  sections.push(summary.videoTitle || 'YouTube Video Summary');
  sections.push('='.repeat(summary.videoTitle?.length || 25));
  sections.push('');
  sections.push(`Video: ${summary.videoUrl}`);
  sections.push(`Mode: ${summary.mode}`);
  sections.push(`Generated: ${new Date(summary.createdAt).toLocaleString()}`);
  sections.push('');
  sections.push('-'.repeat(60));
  sections.push('');
  sections.push(summary.content);
  sections.push('');

  if (summary.timestamps && summary.timestamps.length > 0) {
    sections.push('KEY TIMESTAMPS:');
    summary.timestamps.forEach((ts) => {
      sections.push(`  ${ts.time} - ${ts.text}`);
    });
    sections.push('');
  }

  return sections.join('\n');
}

/**
 * Export summary in Notion-compatible format
 */
export function exportAsNotion(summary: Summary): string {
  const sections: string[] = [];

  // Notion page title format
  sections.push(`# ${summary.videoTitle || 'YouTube Video Summary'}\n`);

  // Properties (Notion-style)
  sections.push(`**📹 Video:** [Watch on YouTube](${summary.videoUrl})`);
  sections.push(`**🎯 Mode:** ${summary.mode}`);
  sections.push(`**📅 Date:** ${new Date(summary.createdAt).toLocaleDateString()}\n`);

  // Divider
  sections.push(`---\n`);

  // Summary in callout block
  sections.push(`> **Summary**`);
  sections.push(`> ${summary.content.replace(/\n/g, '\n> ')}\n`);

  // Timestamps as toggle list
  if (summary.timestamps && summary.timestamps.length > 0) {
    sections.push(`## 🕐 Key Timestamps\n`);
    summary.timestamps.forEach((ts) => {
      sections.push(`- [ ] **${ts.time}** ${ts.text}`);
    });
    sections.push('');
  }

  // Citations as numbered list
  if (summary.citations && summary.citations.length > 0) {
    sections.push(`## 📚 Sources\n`);
    summary.citations.forEach((citation, idx) => {
      sections.push(`${idx + 1}. ${citation}`);
    });
  }

  return sections.join('\n');
}

/**
 * Export summary in Obsidian-compatible format
 */
export function exportAsObsidian(summary: Summary): string {
  const sections: string[] = [];

  // Frontmatter (YAML)
  sections.push('---');
  sections.push(`title: "${summary.videoTitle || 'YouTube Video Summary'}"`);
  sections.push(`video_id: "${summary.videoId}"`);
  sections.push(`url: "${summary.videoUrl}"`);
  sections.push(`mode: "${summary.mode}"`);
  sections.push(`created: ${new Date(summary.createdAt).toISOString()}`);
  sections.push(`tags: [youtube, summary, ai-generated]`);
  sections.push('---\n');

  // Content
  sections.push(`# ${summary.videoTitle || 'YouTube Video Summary'}\n`);
  sections.push(`🔗 [Watch Video](${summary.videoUrl})\n`);
  sections.push(`## Summary\n`);
  sections.push(summary.content);
  sections.push('');

  // Timestamps with Obsidian links
  if (summary.timestamps && summary.timestamps.length > 0) {
    sections.push(`## Timestamps\n`);
    summary.timestamps.forEach((ts) => {
      sections.push(`- \`${ts.time}\` ${ts.text}`);
    });
    sections.push('');
  }

  // Citations with backlinks
  if (summary.citations && summary.citations.length > 0) {
    sections.push(`## References\n`);
    summary.citations.forEach((citation) => {
      sections.push(`- ${citation}`);
    });
  }

  return sections.join('\n');
}

/**
 * Download file helper
 */
export function downloadFile(content: string, filename: string, mimeType: string = 'text/plain') {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Export summary with format selection
 */
export function exportSummary(
  summary: Summary,
  format: 'markdown' | 'json' | 'text' | 'notion' | 'obsidian'
) {
  const exporters = {
    markdown: {
      content: exportAsMarkdown(summary),
      filename: `summary-${summary.id}.md`,
      mimeType: 'text/markdown',
    },
    json: {
      content: exportAsJSON(summary),
      filename: `summary-${summary.id}.json`,
      mimeType: 'application/json',
    },
    text: {
      content: exportAsText(summary),
      filename: `summary-${summary.id}.txt`,
      mimeType: 'text/plain',
    },
    notion: {
      content: exportAsNotion(summary),
      filename: `summary-${summary.id}-notion.md`,
      mimeType: 'text/markdown',
    },
    obsidian: {
      content: exportAsObsidian(summary),
      filename: `summary-${summary.id}-obsidian.md`,
      mimeType: 'text/markdown',
    },
  };

  const exporter = exporters[format];
  downloadFile(exporter.content, exporter.filename, exporter.mimeType);
}

/**
 * Copy to clipboard helper
 */
export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch (error) {
    console.error('Failed to copy to clipboard:', error);
    return false;
  }
}
